name: Format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Personal access token is required to get around the protected main branch restriction
          # Generate the token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          # with contents and action permissions
          # Add it here https://github.com/nirtamir2/solid-start-starter/settings/secrets/actions/new
          token: ${{ secrets.PAT }}

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Format
        run: pnpm run format

      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format"
